#!/usr/local/bin/python3

from parser import Parser, Command
from code_writer import CodeWriter
import sys
import os


filename = sys.argv[1]
path = os.path.dirname(filename)
basename = os.path.basename(filename).split('.')[0]
output_filename = f'{path}/{basename}.asm'

def main():
    print(f'Hello I read in file {filename} and I am writing to {output_filename}')
    parser = Parser(filename)
    writer = CodeWriter(output_filename)

    while (parser.has_more_commands()):
        current_command = parser.advance()
        print(f'current command is {current_command}')
        if parser.commandType() == Command.C_PUSH or parser.commandType() == Command.C_POP:
            writer.writePushPop(current_command) # why isn't this arg1, arg2?
        elif parser.commandType() == Command.C_ARITHMETIC:
            writer.writeArithmetic(parser.arg1())
        elif parser.commandType() == Command.C_LABEL:
            writer.writeLabel(parser.arg2())
        elif parser.commandType() == Command.C_IF:
            writer.writeIf(parser.arg2())
        elif parser.commandType() == Command.C_GOTO:
            writer.writeGoto(parser.arg2())


if __name__ == '__main__':
    main()
